# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adam/COMSE6424/avnet01/avnet01.srcs/sources_1/bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xci
# IP: The module: 'System_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adam/COMSE6424/avnet01/avnet01.srcs/sources_1/bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/adam/COMSE6424/avnet01/avnet01.srcs/sources_1/bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xci
# IP: The module: 'System_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adam/COMSE6424/avnet01/avnet01.srcs/sources_1/bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
