# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_2 || ORIG_REF_NAME==System_processing_system7_0_2} -quiet] -quiet

# XDC: bd/System/System_ooc.xdc
