set_property SRC_FILE_INFO {cfile:/home/adam/COMSE6424/avnet01/avnet01.srcs/sources_1/bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xdc rfile:../../../avnet01.srcs/sources_1/bd/System/ip/System_processing_system7_0_2/System_processing_system7_0_2.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
